// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestReducerHandler(ReducerEventContext ctx);
        public event TestReducerHandler? OnTestReducer;

        public void TestReducer()
        {
            conn.InternalCallReducer(new Reducer.TestReducer(), this.SetCallReducerFlags.TestReducerFlags);
        }

        public bool InvokeTestReducer(ReducerEventContext ctx, Reducer.TestReducer args)
        {
            if (OnTestReducer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTestReducer(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestReducer : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "TestReducer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestReducerFlags;
        public void TestReducer(CallReducerFlags flags) => TestReducerFlags = flags;
    }
}
