// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountCustomizationHandle : RemoteTableHandle<EventContext, AccountCustomization>
        {
            protected override string RemoteTableName => "AccountCustomization";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AccountCustomization row) => row.AccountId;

                public AccountIdUniqueIndex(AccountCustomizationHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            public sealed class LastActiveTimeIndex : BTreeIndexBase<SpacetimeDB.Timestamp>
            {
                protected override SpacetimeDB.Timestamp GetKey(AccountCustomization row) => row.LastActiveTime;

                public LastActiveTimeIndex(AccountCustomizationHandle table) : base(table) { }
            }

            public readonly LastActiveTimeIndex LastActiveTime;

            internal AccountCustomizationHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                LastActiveTime = new(this);
            }

            protected override object GetPrimaryKey(AccountCustomization row) => row.AccountId;
        }

        public readonly AccountCustomizationHandle AccountCustomization;
    }
}
