// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountBidHandle : RemoteTableHandle<EventContext, AccountBid>
        {
            protected override string RemoteTableName => "AccountBid";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AccountBid row) => row.AccountId;

                public AccountIdUniqueIndex(AccountBidHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal AccountBidHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(AccountBid row) => row.AccountId;
        }

        public readonly AccountBidHandle AccountBid;
    }
}
