// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountSeqHandle : RemoteTableHandle<EventContext, AccountSeq>
        {
            protected override string RemoteTableName => "AccountSeq";

            public sealed class IdSUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AccountSeq row) => row.IdS;

                public IdSUniqueIndex(AccountSeqHandle table) : base(table) { }
            }

            public readonly IdSUniqueIndex IdS;

            internal AccountSeqHandle(DbConnection conn) : base(conn)
            {
                IdS = new(this);
            }

            protected override object GetPrimaryKey(AccountSeq row) => row.IdS;
        }

        public readonly AccountSeqHandle AccountSeq;
    }
}
