// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminHandle : RemoteTableHandle<EventContext, Admin>
        {
            protected override string RemoteTableName => "Admin";

            public sealed class AdminIdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Admin row) => row.AdminIdentity;

                public AdminIdentityUniqueIndex(AdminHandle table) : base(table) { }
            }

            public readonly AdminIdentityUniqueIndex AdminIdentity;

            internal AdminHandle(DbConnection conn) : base(conn)
            {
                AdminIdentity = new(this);
            }

            protected override object GetPrimaryKey(Admin row) => row.AdminIdentity;
        }

        public readonly AdminHandle Admin;
    }
}
