// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AuthFrameHandle : RemoteTableHandle<EventContext, AuthFrame>
        {
            protected override string RemoteTableName => "AuthFrame";

            public sealed class SeqUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(AuthFrame row) => row.Seq;

                public SeqUniqueIndex(AuthFrameHandle table) : base(table) { }
            }

            public readonly SeqUniqueIndex Seq;

            internal AuthFrameHandle(DbConnection conn) : base(conn)
            {
                Seq = new(this);
            }

            protected override object GetPrimaryKey(AuthFrame row) => row.Seq;
        }

        public readonly AuthFrameHandle AuthFrame;
    }
}
