// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseCfgHandle : RemoteTableHandle<EventContext, BaseCfg>
        {
            protected override string RemoteTableName => "BaseCfg";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BaseCfg row) => row.Id;

                public IdUniqueIndex(BaseCfgHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BaseCfgHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BaseCfg row) => row.Id;
        }

        public readonly BaseCfgHandle BaseCfg;
    }
}
