// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseCfgSHandle : RemoteTableHandle<EventContext, BaseCfgS>
        {
            protected override string RemoteTableName => "BaseCfgS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BaseCfgS row) => row.Id;

                public IdUniqueIndex(BaseCfgSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BaseCfgSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BaseCfgS row) => row.Id;
        }

        public readonly BaseCfgSHandle BaseCfgS;
    }
}
