// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BidConfigSHandle : RemoteTableHandle<EventContext, BidConfigS>
        {
            protected override string RemoteTableName => "BidConfigS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BidConfigS row) => row.Id;

                public IdUniqueIndex(BidConfigSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BidConfigSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BidConfigS row) => row.Id;
        }

        public readonly BidConfigSHandle BidConfigS;
    }
}
