// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BiddingStateSHandle : RemoteTableHandle<EventContext, BiddingStateS>
        {
            protected override string RemoteTableName => "BiddingStateS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BiddingStateS row) => row.Id;

                public IdUniqueIndex(BiddingStateSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BiddingStateSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BiddingStateS row) => row.Id;
        }

        public readonly BiddingStateSHandle BiddingStateS;
    }
}
