// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BidTimeSHandle : RemoteTableHandle<EventContext, BidTimeS>
        {
            protected override string RemoteTableName => "BidTimeS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BidTimeS row) => row.Id;

                public IdUniqueIndex(BidTimeSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BidTimeSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BidTimeS row) => row.Id;
        }

        public readonly BidTimeSHandle BidTimeS;
    }
}
