// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClockHandle : RemoteTableHandle<EventContext, Clock>
        {
            protected override string RemoteTableName => "Clock";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(Clock row) => row.Id;

                public IdUniqueIndex(ClockHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClockHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Clock row) => row.Id;
        }

        public readonly ClockHandle Clock;
    }
}
