// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClockScheduleHandle : RemoteTableHandle<EventContext, ClockSchedule>
        {
            protected override string RemoteTableName => "ClockSchedule";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClockSchedule row) => row.Id;

                public IdUniqueIndex(ClockScheduleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClockScheduleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ClockSchedule row) => row.Id;
        }

        public readonly ClockScheduleHandle ClockSchedule;
    }
}
