// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeterminismSnapSHandle : RemoteTableHandle<EventContext, DeterminismSnapS>
        {
            protected override string RemoteTableName => "DeterminismSnapS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(DeterminismSnapS row) => row.Id;

                public IdUniqueIndex(DeterminismSnapSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DeterminismSnapSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DeterminismSnapS row) => row.Id;
        }

        public readonly DeterminismSnapSHandle DeterminismSnapS;
    }
}
