// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeterminismSnapScheduleHandle : RemoteTableHandle<EventContext, DeterminismSnapSchedule>
        {
            protected override string RemoteTableName => "DeterminismSnapSchedule";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeterminismSnapSchedule row) => row.Id;

                public IdUniqueIndex(DeterminismSnapScheduleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DeterminismSnapScheduleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DeterminismSnapSchedule row) => row.Id;
        }

        public readonly DeterminismSnapScheduleHandle DeterminismSnapSchedule;
    }
}
