// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DynamicSpsHandle : RemoteTableHandle<EventContext, DynamicSps>
        {
            protected override string RemoteTableName => "DynamicSPS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(DynamicSps row) => row.Id;

                public IdUniqueIndex(DynamicSpsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DynamicSpsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DynamicSps row) => row.Id;
        }

        public readonly DynamicSpsHandle DynamicSps;
    }
}
