// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTileDataHandle : RemoteTableHandle<EventContext, GameTileData>
        {
            protected override string RemoteTableName => "GameTileData";

            public sealed class UnityPrefabGuidUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(GameTileData row) => row.UnityPrefabGuid;

                public UnityPrefabGuidUniqueIndex(GameTileDataHandle table) : base(table) { }
            }

            public readonly UnityPrefabGuidUniqueIndex UnityPrefabGuid;

            internal GameTileDataHandle(DbConnection conn) : base(conn)
            {
                UnityPrefabGuid = new(this);
            }

            protected override object GetPrimaryKey(GameTileData row) => row.UnityPrefabGuid;
        }

        public readonly GameTileDataHandle GameTileData;
    }
}
