// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameCoreSnapHandle : RemoteTableHandle<EventContext, GameCoreSnap>
        {
            protected override string RemoteTableName => "GameCoreSnap";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(GameCoreSnap row) => row.Id;

                public IdUniqueIndex(GameCoreSnapHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameCoreSnapHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameCoreSnap row) => row.Id;
        }

        public readonly GameCoreSnapHandle GameCoreSnap;
    }
}
