// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTileHandle : RemoteTableHandle<EventContext, GameTile>
        {
            protected override string RemoteTableName => "GameTile";

            public sealed class UnityPrefabGuidUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(GameTile row) => row.UnityPrefabGuid;

                public UnityPrefabGuidUniqueIndex(GameTileHandle table) : base(table) { }
            }

            public readonly UnityPrefabGuidUniqueIndex UnityPrefabGuid;

            internal GameTileHandle(DbConnection conn) : base(conn)
            {
                UnityPrefabGuid = new(this);
            }

            protected override object GetPrimaryKey(GameTile row) => row.UnityPrefabGuid;
        }

        public readonly GameTileHandle GameTile;
    }
}
