// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameplayFinishedFlagSHandle : RemoteTableHandle<EventContext, GameplayFinishedFlagS>
        {
            protected override string RemoteTableName => "GameplayFinishedFlagS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(GameplayFinishedFlagS row) => row.Id;

                public IdUniqueIndex(GameplayFinishedFlagSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameplayFinishedFlagSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameplayFinishedFlagS row) => row.Id;
        }

        public readonly GameplayFinishedFlagSHandle GameplayFinishedFlagS;
    }
}
