// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InputFrameHandle : RemoteTableHandle<EventContext, InputFrame>
        {
            protected override string RemoteTableName => "InputFrame";

            public sealed class SeqUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(InputFrame row) => row.Seq;

                public SeqUniqueIndex(InputFrameHandle table) : base(table) { }
            }

            public readonly SeqUniqueIndex Seq;

            internal InputFrameHandle(DbConnection conn) : base(conn)
            {
                Seq = new(this);
            }

            protected override object GetPrimaryKey(InputFrame row) => row.Seq;
        }

        public readonly InputFrameHandle InputFrame;
    }
}
