// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LastAuthFrameTimestampHandle : RemoteTableHandle<EventContext, LastAuthFrameTimestamp>
        {
            protected override string RemoteTableName => "LastAuthFrameTimestamp";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(LastAuthFrameTimestamp row) => row.Id;

                public IdUniqueIndex(LastAuthFrameTimestampHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal LastAuthFrameTimestampHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(LastAuthFrameTimestamp row) => row.Id;
        }

        public readonly LastAuthFrameTimestampHandle LastAuthFrameTimestamp;
    }
}
