// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LevelFileDataHandle : RemoteTableHandle<EventContext, LevelFileData>
        {
            protected override string RemoteTableName => "LevelFileData";

            public sealed class UnityPrefabGuidUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(LevelFileData row) => row.UnityPrefabGuid;

                public UnityPrefabGuidUniqueIndex(LevelFileDataHandle table) : base(table) { }
            }

            public readonly UnityPrefabGuidUniqueIndex UnityPrefabGuid;

            internal LevelFileDataHandle(DbConnection conn) : base(conn)
            {
                UnityPrefabGuid = new(this);
            }

            protected override object GetPrimaryKey(LevelFileData row) => row.UnityPrefabGuid;
        }

        public readonly LevelFileDataHandle LevelFileData;
    }
}
