// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LevelFileHandle : RemoteTableHandle<EventContext, LevelFile>
        {
            protected override string RemoteTableName => "LevelFile";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(LevelFile row) => row.Id;

                public IdUniqueIndex(LevelFileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal LevelFileHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(LevelFile row) => row.Id;
        }

        public readonly LevelFileHandle LevelFile;
    }
}
