// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NextGameBidCfgSHandle : RemoteTableHandle<EventContext, NextGameBidCfgS>
        {
            protected override string RemoteTableName => "NextGameBidCfgS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(NextGameBidCfgS row) => row.Id;

                public IdUniqueIndex(NextGameBidCfgSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NextGameBidCfgSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NextGameBidCfgS row) => row.Id;
        }

        public readonly NextGameBidCfgSHandle NextGameBidCfgS;
    }
}
