// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ScoreboardEntryHandle : RemoteTableHandle<EventContext, ScoreboardEntry>
        {
            protected override string RemoteTableName => "ScoreboardEntry";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ScoreboardEntry row) => row.AccountId;

                public AccountIdUniqueIndex(ScoreboardEntryHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal ScoreboardEntryHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(ScoreboardEntry row) => row.AccountId;
        }

        public readonly ScoreboardEntryHandle ScoreboardEntry;
    }
}
