// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SeqHandle : RemoteTableHandle<EventContext, Seq>
        {
            protected override string RemoteTableName => "Seq";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(Seq row) => row.Id;

                public IdUniqueIndex(SeqHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SeqHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Seq row) => row.Id;
        }

        public readonly SeqHandle Seq;
    }
}
