// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ServerCfgSHandle : RemoteTableHandle<EventContext, ServerCfgS>
        {
            protected override string RemoteTableName => "ServerCfgS";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ServerCfgS row) => row.Id;

                public IdUniqueIndex(ServerCfgSHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ServerCfgSHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ServerCfgS row) => row.Id;
        }

        public readonly ServerCfgSHandle ServerCfgS;
    }
}
