// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionHandle : RemoteTableHandle<EventContext, Session>
        {
            protected override string RemoteTableName => "Session";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Session row) => row.Identity;

                public IdentityUniqueIndex(SessionHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal SessionHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Session row) => row.Identity;
        }

        public readonly SessionHandle Session;
    }
}
