// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StepsSinceLastBatchHandle : RemoteTableHandle<EventContext, StepsSinceLastBatch>
        {
            protected override string RemoteTableName => "StepsSinceLastBatch";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(StepsSinceLastBatch row) => row.Id;

                public IdUniqueIndex(StepsSinceLastBatchHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StepsSinceLastBatchHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(StepsSinceLastBatch row) => row.Id;
        }

        public readonly StepsSinceLastBatchHandle StepsSinceLastBatch;
    }
}
