// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StepsSinceLastAuthFrameHandle : RemoteTableHandle<EventContext, StepsSinceLastAuthFrame>
        {
            protected override string RemoteTableName => "StepsSinceLastAuthFrame";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(StepsSinceLastAuthFrame row) => row.Id;

                public IdUniqueIndex(StepsSinceLastAuthFrameHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StepsSinceLastAuthFrameHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(StepsSinceLastAuthFrame row) => row.Id;
        }

        public readonly StepsSinceLastAuthFrameHandle StepsSinceLastAuthFrame;
    }
}
