// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ThroneTileDataHandle : RemoteTableHandle<EventContext, ThroneTileData>
        {
            protected override string RemoteTableName => "ThroneTileData";

            public sealed class UnityPrefabGuidUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ThroneTileData row) => row.UnityPrefabGuid;

                public UnityPrefabGuidUniqueIndex(ThroneTileDataHandle table) : base(table) { }
            }

            public readonly UnityPrefabGuidUniqueIndex UnityPrefabGuid;

            internal ThroneTileDataHandle(DbConnection conn) : base(conn)
            {
                UnityPrefabGuid = new(this);
            }

            protected override object GetPrimaryKey(ThroneTileData row) => row.UnityPrefabGuid;
        }

        public readonly ThroneTileDataHandle ThroneTileData;
    }
}
