// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  id: __t.u64(),
  isConnected: __t.bool(),
  marbles: __t.u32(),
  points: __t.u32(),
  gold: __t.u32(),
  firstLoginBonusClaimed: __t.bool(),
  isMember: __t.bool(),
  dailyRewardClaimStreak: __t.u16(),
  lastDailyRewardClaimDay: __t.i64(),
});
