// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Account = {
  identity: __Identity,
  id: bigint,
  isConnected: boolean,
  marbles: number,
  points: number,
  gold: number,
  firstLoginBonusClaimed: boolean,
  isMember: boolean,
  dailyRewardClaimStreak: bigint,
  lastDailyRewardClaimDay: bigint,
};
let _cached_Account_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Account = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Account_type_value) return _cached_Account_type_value;
    _cached_Account_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Account_type_value.value.elements.push(
      { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "id", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "isConnected", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "marbles", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "points", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "gold", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "firstLoginBonusClaimed", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "isMember", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "dailyRewardClaimStreak", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "lastDailyRewardClaimDay", algebraicType: __AlgebraicTypeValue.I64 },
    );
    return _cached_Account_type_value;
  },

  serialize(writer: __BinaryWriter, value: Account): void {
    __AlgebraicTypeValue.serializeValue(writer, Account.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Account {
    return __AlgebraicTypeValue.deserializeValue(reader, Account.getTypeScriptAlgebraicType());
  },

}

export default Account;


