// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("BaseCfgS", {
  id: __t.u8(),
  clockIntervalSec: __t.f64(),
  determinismSnapIntervalSec: __t.f64(),
  targetStepsPerSecond: __t.u16(),
  physicsStepsPerBatch: __t.u16(),
  stepsPerAuthFrame: __t.u16(),
  authFrameTimeErrorThresholdSec: __t.f64(),
  logInputFrameTimes: __t.bool(),
  logAuthFrameTimeDiffs: __t.bool(),
  gcCacheAccountTimeoutMinutes: __t.f64(),
  dayRewardStreak1Marbles: __t.u16(),
  dayRewardStreak2Marbles: __t.u16(),
  dayRewardStreak3Marbles: __t.u16(),
  dayRewardStreak4Marbles: __t.u16(),
  dayRewardStreak5Marbles: __t.u16(),
  dayRewardStreak6Marbles: __t.u16(),
  dayRewardStreak7Marbles: __t.u16(),
});


