// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  clockIntervalSec: __t.f64(),
  targetStepsPerSecond: __t.u16(),
  physicsStepsPerBatch: __t.u16(),
  stepsPerAuthFrame: __t.u16(),
  authFrameTimeErrorThresholdSec: __t.f64(),
  logInputFrameTimes: __t.bool(),
  logAuthFrameTimeDiffs: __t.bool(),
  gcCacheAccountTimeoutMinutes: __t.f64(),
});
