// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { ClockUpdate } from "./clock_update_reducer.ts";
export { ClockUpdate };
import { CloseAndCycleGameTile } from "./close_and_cycle_game_tile_reducer.ts";
export { CloseAndCycleGameTile };
import { Connect } from "./connect_reducer.ts";
export { Connect };
import { Disconnect } from "./disconnect_reducer.ts";
export { Disconnect };
import { IncrementPfpVersion } from "./increment_pfp_version_reducer.ts";
export { IncrementPfpVersion };
import { SetUsername } from "./set_username_reducer.ts";
export { SetUsername };
import { UpsertAccount } from "./upsert_account_reducer.ts";
export { UpsertAccount };
import { UpsertAccountSeq } from "./upsert_account_seq_reducer.ts";
export { UpsertAccountSeq };
import { UpsertAuthFrame } from "./upsert_auth_frame_reducer.ts";
export { UpsertAuthFrame };
import { UpsertBaseCfg } from "./upsert_base_cfg_reducer.ts";
export { UpsertBaseCfg };
import { UpsertInputCollector } from "./upsert_input_collector_reducer.ts";
export { UpsertInputCollector };
import { UpsertInputFrame } from "./upsert_input_frame_reducer.ts";
export { UpsertInputFrame };
import { UpsertLevelFileData } from "./upsert_level_file_data_reducer.ts";
export { UpsertLevelFileData };

// Import and reexport all table handle types
import { AccountTableHandle } from "./account_table.ts";
export { AccountTableHandle };
import { AccountCustomizationTableHandle } from "./account_customization_table.ts";
export { AccountCustomizationTableHandle };
import { AccountSeqTableHandle } from "./account_seq_table.ts";
export { AccountSeqTableHandle };
import { AdminTableHandle } from "./admin_table.ts";
export { AdminTableHandle };
import { AuthFrameTableHandle } from "./auth_frame_table.ts";
export { AuthFrameTableHandle };
import { BaseCfgTableHandle } from "./base_cfg_table.ts";
export { BaseCfgTableHandle };
import { ClockTableHandle } from "./clock_table.ts";
export { ClockTableHandle };
import { ClockScheduleTableHandle } from "./clock_schedule_table.ts";
export { ClockScheduleTableHandle };
import { DeterminismCheckTableHandle } from "./determinism_check_table.ts";
export { DeterminismCheckTableHandle };
import { GameCoreSnapTableHandle } from "./game_core_snap_table.ts";
export { GameCoreSnapTableHandle };
import { InputCollectorTableHandle } from "./input_collector_table.ts";
export { InputCollectorTableHandle };
import { InputFrameTableHandle } from "./input_frame_table.ts";
export { InputFrameTableHandle };
import { LastAuthFrameTimestampTableHandle } from "./last_auth_frame_timestamp_table.ts";
export { LastAuthFrameTimestampTableHandle };
import { LevelFileDataTableHandle } from "./level_file_data_table.ts";
export { LevelFileDataTableHandle };
import { SeqTableHandle } from "./seq_table.ts";
export { SeqTableHandle };
import { StepsSinceLastAuthFrameTableHandle } from "./steps_since_last_auth_frame_table.ts";
export { StepsSinceLastAuthFrameTableHandle };
import { StepsSinceLastBatchTableHandle } from "./steps_since_last_batch_table.ts";
export { StepsSinceLastBatchTableHandle };

// Import and reexport all types
import { Account } from "./account_type.ts";
export { Account };
import { AccountCustomization } from "./account_customization_type.ts";
export { AccountCustomization };
import { AccountSeq } from "./account_seq_type.ts";
export { AccountSeq };
import { Admin } from "./admin_type.ts";
export { Admin };
import { AuthFrame } from "./auth_frame_type.ts";
export { AuthFrame };
import { BaseCfg } from "./base_cfg_type.ts";
export { BaseCfg };
import { Clock } from "./clock_type.ts";
export { Clock };
import { ClockSchedule } from "./clock_schedule_type.ts";
export { ClockSchedule };
import { DeterminismCheck } from "./determinism_check_type.ts";
export { DeterminismCheck };
import { GameCoreSnap } from "./game_core_snap_type.ts";
export { GameCoreSnap };
import { InputCollector } from "./input_collector_type.ts";
export { InputCollector };
import { InputFrame } from "./input_frame_type.ts";
export { InputFrame };
import { LastAuthFrameTimestamp } from "./last_auth_frame_timestamp_type.ts";
export { LastAuthFrameTimestamp };
import { LevelFileData } from "./level_file_data_type.ts";
export { LevelFileData };
import { Seq } from "./seq_type.ts";
export { Seq };
import { StepsSinceLastAuthFrame } from "./steps_since_last_auth_frame_type.ts";
export { StepsSinceLastAuthFrame };
import { StepsSinceLastBatch } from "./steps_since_last_batch_type.ts";
export { StepsSinceLastBatch };

const REMOTE_MODULE = {
  tables: {
    Account: {
      tableName: "Account" as const,
      rowType: Account.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (Account.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    AccountCustomization: {
      tableName: "AccountCustomization" as const,
      rowType: AccountCustomization.getTypeScriptAlgebraicType(),
      primaryKey: "accountId",
      primaryKeyInfo: {
        colName: "accountId",
        colType: (AccountCustomization.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    AccountSeq: {
      tableName: "AccountSeq" as const,
      rowType: AccountSeq.getTypeScriptAlgebraicType(),
      primaryKey: "idS",
      primaryKeyInfo: {
        colName: "idS",
        colType: (AccountSeq.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    Admin: {
      tableName: "Admin" as const,
      rowType: Admin.getTypeScriptAlgebraicType(),
      primaryKey: "adminIdentity",
      primaryKeyInfo: {
        colName: "adminIdentity",
        colType: (Admin.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    AuthFrame: {
      tableName: "AuthFrame" as const,
      rowType: AuthFrame.getTypeScriptAlgebraicType(),
      primaryKey: "seq",
      primaryKeyInfo: {
        colName: "seq",
        colType: (AuthFrame.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    BaseCfg: {
      tableName: "BaseCfg" as const,
      rowType: BaseCfg.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (BaseCfg.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    Clock: {
      tableName: "Clock" as const,
      rowType: Clock.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Clock.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    ClockSchedule: {
      tableName: "ClockSchedule" as const,
      rowType: ClockSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (ClockSchedule.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    DeterminismCheck: {
      tableName: "DeterminismCheck" as const,
      rowType: DeterminismCheck.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (DeterminismCheck.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    GameCoreSnap: {
      tableName: "GameCoreSnap" as const,
      rowType: GameCoreSnap.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (GameCoreSnap.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    InputCollector: {
      tableName: "InputCollector" as const,
      rowType: InputCollector.getTypeScriptAlgebraicType(),
    },
    InputFrame: {
      tableName: "InputFrame" as const,
      rowType: InputFrame.getTypeScriptAlgebraicType(),
      primaryKey: "seq",
      primaryKeyInfo: {
        colName: "seq",
        colType: (InputFrame.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    LastAuthFrameTimestamp: {
      tableName: "LastAuthFrameTimestamp" as const,
      rowType: LastAuthFrameTimestamp.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (LastAuthFrameTimestamp.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    LevelFileData: {
      tableName: "LevelFileData" as const,
      rowType: LevelFileData.getTypeScriptAlgebraicType(),
      primaryKey: "unityPrefabGuid",
      primaryKeyInfo: {
        colName: "unityPrefabGuid",
        colType: (LevelFileData.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    Seq: {
      tableName: "Seq" as const,
      rowType: Seq.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Seq.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    StepsSinceLastAuthFrame: {
      tableName: "StepsSinceLastAuthFrame" as const,
      rowType: StepsSinceLastAuthFrame.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (StepsSinceLastAuthFrame.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    StepsSinceLastBatch: {
      tableName: "StepsSinceLastBatch" as const,
      rowType: StepsSinceLastBatch.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (StepsSinceLastBatch.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    ClockUpdate: {
      reducerName: "ClockUpdate",
      argsType: ClockUpdate.getTypeScriptAlgebraicType(),
    },
    CloseAndCycleGameTile: {
      reducerName: "CloseAndCycleGameTile",
      argsType: CloseAndCycleGameTile.getTypeScriptAlgebraicType(),
    },
    Connect: {
      reducerName: "Connect",
      argsType: Connect.getTypeScriptAlgebraicType(),
    },
    Disconnect: {
      reducerName: "Disconnect",
      argsType: Disconnect.getTypeScriptAlgebraicType(),
    },
    IncrementPfpVersion: {
      reducerName: "IncrementPfpVersion",
      argsType: IncrementPfpVersion.getTypeScriptAlgebraicType(),
    },
    SetUsername: {
      reducerName: "SetUsername",
      argsType: SetUsername.getTypeScriptAlgebraicType(),
    },
    UpsertAccount: {
      reducerName: "UpsertAccount",
      argsType: UpsertAccount.getTypeScriptAlgebraicType(),
    },
    UpsertAccountSeq: {
      reducerName: "UpsertAccountSeq",
      argsType: UpsertAccountSeq.getTypeScriptAlgebraicType(),
    },
    UpsertAuthFrame: {
      reducerName: "UpsertAuthFrame",
      argsType: UpsertAuthFrame.getTypeScriptAlgebraicType(),
    },
    UpsertBaseCfg: {
      reducerName: "UpsertBaseCfg",
      argsType: UpsertBaseCfg.getTypeScriptAlgebraicType(),
    },
    UpsertInputCollector: {
      reducerName: "UpsertInputCollector",
      argsType: UpsertInputCollector.getTypeScriptAlgebraicType(),
    },
    UpsertInputFrame: {
      reducerName: "UpsertInputFrame",
      argsType: UpsertInputFrame.getTypeScriptAlgebraicType(),
    },
    UpsertLevelFileData: {
      reducerName: "UpsertLevelFileData",
      argsType: UpsertLevelFileData.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "ClockUpdate", args: ClockUpdate }
| { name: "CloseAndCycleGameTile", args: CloseAndCycleGameTile }
| { name: "Connect", args: Connect }
| { name: "Disconnect", args: Disconnect }
| { name: "IncrementPfpVersion", args: IncrementPfpVersion }
| { name: "SetUsername", args: SetUsername }
| { name: "UpsertAccount", args: UpsertAccount }
| { name: "UpsertAccountSeq", args: UpsertAccountSeq }
| { name: "UpsertAuthFrame", args: UpsertAuthFrame }
| { name: "UpsertBaseCfg", args: UpsertBaseCfg }
| { name: "UpsertInputCollector", args: UpsertInputCollector }
| { name: "UpsertInputFrame", args: UpsertInputFrame }
| { name: "UpsertLevelFileData", args: UpsertLevelFileData }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  clockUpdate(schedule: ClockSchedule) {
    const __args = { schedule };
    let __writer = new __BinaryWriter(1024);
    ClockUpdate.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("ClockUpdate", __argsBuffer, this.setCallReducerFlags.clockUpdateFlags);
  }

  onClockUpdate(callback: (ctx: ReducerEventContext, schedule: ClockSchedule) => void) {
    this.connection.onReducer("ClockUpdate", callback);
  }

  removeOnClockUpdate(callback: (ctx: ReducerEventContext, schedule: ClockSchedule) => void) {
    this.connection.offReducer("ClockUpdate", callback);
  }

  closeAndCycleGameTile(worldId: number) {
    const __args = { worldId };
    let __writer = new __BinaryWriter(1024);
    CloseAndCycleGameTile.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("CloseAndCycleGameTile", __argsBuffer, this.setCallReducerFlags.closeAndCycleGameTileFlags);
  }

  onCloseAndCycleGameTile(callback: (ctx: ReducerEventContext, worldId: number) => void) {
    this.connection.onReducer("CloseAndCycleGameTile", callback);
  }

  removeOnCloseAndCycleGameTile(callback: (ctx: ReducerEventContext, worldId: number) => void) {
    this.connection.offReducer("CloseAndCycleGameTile", callback);
  }

  onConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("Connect", callback);
  }

  removeOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("Connect", callback);
  }

  onDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("Disconnect", callback);
  }

  removeOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("Disconnect", callback);
  }

  incrementPfpVersion() {
    this.connection.callReducer("IncrementPfpVersion", new Uint8Array(0), this.setCallReducerFlags.incrementPfpVersionFlags);
  }

  onIncrementPfpVersion(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("IncrementPfpVersion", callback);
  }

  removeOnIncrementPfpVersion(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("IncrementPfpVersion", callback);
  }

  setUsername(username: string, overwriteExisting: boolean) {
    const __args = { username, overwriteExisting };
    let __writer = new __BinaryWriter(1024);
    SetUsername.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("SetUsername", __argsBuffer, this.setCallReducerFlags.setUsernameFlags);
  }

  onSetUsername(callback: (ctx: ReducerEventContext, username: string, overwriteExisting: boolean) => void) {
    this.connection.onReducer("SetUsername", callback);
  }

  removeOnSetUsername(callback: (ctx: ReducerEventContext, username: string, overwriteExisting: boolean) => void) {
    this.connection.offReducer("SetUsername", callback);
  }

  upsertAccount(row: Account) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertAccount.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertAccount", __argsBuffer, this.setCallReducerFlags.upsertAccountFlags);
  }

  onUpsertAccount(callback: (ctx: ReducerEventContext, row: Account) => void) {
    this.connection.onReducer("UpsertAccount", callback);
  }

  removeOnUpsertAccount(callback: (ctx: ReducerEventContext, row: Account) => void) {
    this.connection.offReducer("UpsertAccount", callback);
  }

  upsertAccountSeq(row: AccountSeq) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertAccountSeq.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertAccountSeq", __argsBuffer, this.setCallReducerFlags.upsertAccountSeqFlags);
  }

  onUpsertAccountSeq(callback: (ctx: ReducerEventContext, row: AccountSeq) => void) {
    this.connection.onReducer("UpsertAccountSeq", callback);
  }

  removeOnUpsertAccountSeq(callback: (ctx: ReducerEventContext, row: AccountSeq) => void) {
    this.connection.offReducer("UpsertAccountSeq", callback);
  }

  upsertAuthFrame(row: AuthFrame) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertAuthFrame.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertAuthFrame", __argsBuffer, this.setCallReducerFlags.upsertAuthFrameFlags);
  }

  onUpsertAuthFrame(callback: (ctx: ReducerEventContext, row: AuthFrame) => void) {
    this.connection.onReducer("UpsertAuthFrame", callback);
  }

  removeOnUpsertAuthFrame(callback: (ctx: ReducerEventContext, row: AuthFrame) => void) {
    this.connection.offReducer("UpsertAuthFrame", callback);
  }

  upsertBaseCfg(row: BaseCfg) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertBaseCfg.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertBaseCfg", __argsBuffer, this.setCallReducerFlags.upsertBaseCfgFlags);
  }

  onUpsertBaseCfg(callback: (ctx: ReducerEventContext, row: BaseCfg) => void) {
    this.connection.onReducer("UpsertBaseCfg", callback);
  }

  removeOnUpsertBaseCfg(callback: (ctx: ReducerEventContext, row: BaseCfg) => void) {
    this.connection.offReducer("UpsertBaseCfg", callback);
  }

  upsertInputCollector(row: InputCollector) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertInputCollector.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertInputCollector", __argsBuffer, this.setCallReducerFlags.upsertInputCollectorFlags);
  }

  onUpsertInputCollector(callback: (ctx: ReducerEventContext, row: InputCollector) => void) {
    this.connection.onReducer("UpsertInputCollector", callback);
  }

  removeOnUpsertInputCollector(callback: (ctx: ReducerEventContext, row: InputCollector) => void) {
    this.connection.offReducer("UpsertInputCollector", callback);
  }

  upsertInputFrame(row: InputFrame) {
    const __args = { row };
    let __writer = new __BinaryWriter(1024);
    UpsertInputFrame.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertInputFrame", __argsBuffer, this.setCallReducerFlags.upsertInputFrameFlags);
  }

  onUpsertInputFrame(callback: (ctx: ReducerEventContext, row: InputFrame) => void) {
    this.connection.onReducer("UpsertInputFrame", callback);
  }

  removeOnUpsertInputFrame(callback: (ctx: ReducerEventContext, row: InputFrame) => void) {
    this.connection.offReducer("UpsertInputFrame", callback);
  }

  upsertLevelFileData(levelFileData: LevelFileData) {
    const __args = { levelFileData };
    let __writer = new __BinaryWriter(1024);
    UpsertLevelFileData.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpsertLevelFileData", __argsBuffer, this.setCallReducerFlags.upsertLevelFileDataFlags);
  }

  onUpsertLevelFileData(callback: (ctx: ReducerEventContext, levelFileData: LevelFileData) => void) {
    this.connection.onReducer("UpsertLevelFileData", callback);
  }

  removeOnUpsertLevelFileData(callback: (ctx: ReducerEventContext, levelFileData: LevelFileData) => void) {
    this.connection.offReducer("UpsertLevelFileData", callback);
  }

}

export class SetReducerFlags {
  clockUpdateFlags: __CallReducerFlags = 'FullUpdate';
  clockUpdate(flags: __CallReducerFlags) {
    this.clockUpdateFlags = flags;
  }

  closeAndCycleGameTileFlags: __CallReducerFlags = 'FullUpdate';
  closeAndCycleGameTile(flags: __CallReducerFlags) {
    this.closeAndCycleGameTileFlags = flags;
  }

  incrementPfpVersionFlags: __CallReducerFlags = 'FullUpdate';
  incrementPfpVersion(flags: __CallReducerFlags) {
    this.incrementPfpVersionFlags = flags;
  }

  setUsernameFlags: __CallReducerFlags = 'FullUpdate';
  setUsername(flags: __CallReducerFlags) {
    this.setUsernameFlags = flags;
  }

  upsertAccountFlags: __CallReducerFlags = 'FullUpdate';
  upsertAccount(flags: __CallReducerFlags) {
    this.upsertAccountFlags = flags;
  }

  upsertAccountSeqFlags: __CallReducerFlags = 'FullUpdate';
  upsertAccountSeq(flags: __CallReducerFlags) {
    this.upsertAccountSeqFlags = flags;
  }

  upsertAuthFrameFlags: __CallReducerFlags = 'FullUpdate';
  upsertAuthFrame(flags: __CallReducerFlags) {
    this.upsertAuthFrameFlags = flags;
  }

  upsertBaseCfgFlags: __CallReducerFlags = 'FullUpdate';
  upsertBaseCfg(flags: __CallReducerFlags) {
    this.upsertBaseCfgFlags = flags;
  }

  upsertInputCollectorFlags: __CallReducerFlags = 'FullUpdate';
  upsertInputCollector(flags: __CallReducerFlags) {
    this.upsertInputCollectorFlags = flags;
  }

  upsertInputFrameFlags: __CallReducerFlags = 'FullUpdate';
  upsertInputFrame(flags: __CallReducerFlags) {
    this.upsertInputFrameFlags = flags;
  }

  upsertLevelFileDataFlags: __CallReducerFlags = 'FullUpdate';
  upsertLevelFileData(flags: __CallReducerFlags) {
    this.upsertLevelFileDataFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get account(): AccountTableHandle<'Account'> {
    // clientCache is a private property
    return new AccountTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Account>(REMOTE_MODULE.tables.Account));
  }

  get accountCustomization(): AccountCustomizationTableHandle<'AccountCustomization'> {
    // clientCache is a private property
    return new AccountCustomizationTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AccountCustomization>(REMOTE_MODULE.tables.AccountCustomization));
  }

  get accountSeq(): AccountSeqTableHandle<'AccountSeq'> {
    // clientCache is a private property
    return new AccountSeqTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AccountSeq>(REMOTE_MODULE.tables.AccountSeq));
  }

  get admin(): AdminTableHandle<'Admin'> {
    // clientCache is a private property
    return new AdminTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Admin>(REMOTE_MODULE.tables.Admin));
  }

  get authFrame(): AuthFrameTableHandle<'AuthFrame'> {
    // clientCache is a private property
    return new AuthFrameTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AuthFrame>(REMOTE_MODULE.tables.AuthFrame));
  }

  get baseCfg(): BaseCfgTableHandle<'BaseCfg'> {
    // clientCache is a private property
    return new BaseCfgTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<BaseCfg>(REMOTE_MODULE.tables.BaseCfg));
  }

  get clock(): ClockTableHandle<'Clock'> {
    // clientCache is a private property
    return new ClockTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Clock>(REMOTE_MODULE.tables.Clock));
  }

  get clockSchedule(): ClockScheduleTableHandle<'ClockSchedule'> {
    // clientCache is a private property
    return new ClockScheduleTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ClockSchedule>(REMOTE_MODULE.tables.ClockSchedule));
  }

  get determinismCheck(): DeterminismCheckTableHandle<'DeterminismCheck'> {
    // clientCache is a private property
    return new DeterminismCheckTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<DeterminismCheck>(REMOTE_MODULE.tables.DeterminismCheck));
  }

  get gameCoreSnap(): GameCoreSnapTableHandle<'GameCoreSnap'> {
    // clientCache is a private property
    return new GameCoreSnapTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GameCoreSnap>(REMOTE_MODULE.tables.GameCoreSnap));
  }

  get inputCollector(): InputCollectorTableHandle<'InputCollector'> {
    // clientCache is a private property
    return new InputCollectorTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<InputCollector>(REMOTE_MODULE.tables.InputCollector));
  }

  get inputFrame(): InputFrameTableHandle<'InputFrame'> {
    // clientCache is a private property
    return new InputFrameTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<InputFrame>(REMOTE_MODULE.tables.InputFrame));
  }

  get lastAuthFrameTimestamp(): LastAuthFrameTimestampTableHandle<'LastAuthFrameTimestamp'> {
    // clientCache is a private property
    return new LastAuthFrameTimestampTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<LastAuthFrameTimestamp>(REMOTE_MODULE.tables.LastAuthFrameTimestamp));
  }

  get levelFileData(): LevelFileDataTableHandle<'LevelFileData'> {
    // clientCache is a private property
    return new LevelFileDataTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<LevelFileData>(REMOTE_MODULE.tables.LevelFileData));
  }

  get seq(): SeqTableHandle<'Seq'> {
    // clientCache is a private property
    return new SeqTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Seq>(REMOTE_MODULE.tables.Seq));
  }

  get stepsSinceLastAuthFrame(): StepsSinceLastAuthFrameTableHandle<'StepsSinceLastAuthFrame'> {
    // clientCache is a private property
    return new StepsSinceLastAuthFrameTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<StepsSinceLastAuthFrame>(REMOTE_MODULE.tables.StepsSinceLastAuthFrame));
  }

  get stepsSinceLastBatch(): StepsSinceLastBatchTableHandle<'StepsSinceLastBatch'> {
    // clientCache is a private property
    return new StepsSinceLastBatchTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<StepsSinceLastBatch>(REMOTE_MODULE.tables.StepsSinceLastBatch));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
