// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.0 (commit 49ccb7ac2ae18042057c844591c9749532bc691a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AGiveMarbles from "./a_give_marbles_reducer";
export { AGiveMarbles };
import AInsertBid from "./a_insert_bid_reducer";
export { AInsertBid };
import ASpinLoadGameplayTile from "./a_spin_load_gameplay_tile_reducer";
export { ASpinLoadGameplayTile };
import ClockUpdate from "./clock_update_reducer";
export { ClockUpdate };
import Connect from "./connect_reducer";
export { Connect };
import Disconnect from "./disconnect_reducer";
export { Disconnect };
import IncrementPfpVersion from "./increment_pfp_version_reducer";
export { IncrementPfpVersion };
import PlaceBid from "./place_bid_reducer";
export { PlaceBid };
import SetUsername from "./set_username_reducer";
export { SetUsername };
import UpsertAccount from "./upsert_account_reducer";
export { UpsertAccount };
import UpsertAccountSeq from "./upsert_account_seq_reducer";
export { UpsertAccountSeq };
import UpsertAuthFrame from "./upsert_auth_frame_reducer";
export { UpsertAuthFrame };
import UpsertBaseCfg from "./upsert_base_cfg_reducer";
export { UpsertBaseCfg };
import UpsertGameTile from "./upsert_game_tile_reducer";
export { UpsertGameTile };
import UpsertInputCollector from "./upsert_input_collector_reducer";
export { UpsertInputCollector };
import UpsertInputFrame from "./upsert_input_frame_reducer";
export { UpsertInputFrame };
import UpsertThroneTile from "./upsert_throne_tile_reducer";
export { UpsertThroneTile };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AccountRow from "./account_table";
export { AccountRow };
import AccountBidRow from "./account_bid_table";
export { AccountBidRow };
import AccountCustomizationRow from "./account_customization_table";
export { AccountCustomizationRow };
import AccountSeqRow from "./account_seq_table";
export { AccountSeqRow };
import AdminRow from "./admin_table";
export { AdminRow };
import AuthFrameRow from "./auth_frame_table";
export { AuthFrameRow };
import BaseCfgRow from "./base_cfg_table";
export { BaseCfgRow };
import BidConfigSRow from "./bid_config_s_table";
export { BidConfigSRow };
import BidTimeSRow from "./bid_time_s_table";
export { BidTimeSRow };
import BiddingStateSRow from "./bidding_state_s_table";
export { BiddingStateSRow };
import ClockRow from "./clock_table";
export { ClockRow };
import ClockScheduleRow from "./clock_schedule_table";
export { ClockScheduleRow };
import DeterminismCheckRow from "./determinism_check_table";
export { DeterminismCheckRow };
import GtScoreboardSRow from "./gt_scoreboard_s_table";
export { GtScoreboardSRow };
import GameCoreSnapRow from "./game_core_snap_table";
export { GameCoreSnapRow };
import GameTileDataRow from "./game_tile_data_table";
export { GameTileDataRow };
import InputCollectorRow from "./input_collector_table";
export { InputCollectorRow };
import InputFrameRow from "./input_frame_table";
export { InputFrameRow };
import LastAuthFrameTimestampRow from "./last_auth_frame_timestamp_table";
export { LastAuthFrameTimestampRow };
import MyAccountRow from "./my_account_table";
export { MyAccountRow };
import MySessionKindRow from "./my_session_kind_table";
export { MySessionKindRow };
import ScoreboardEntryRow from "./scoreboard_entry_table";
export { ScoreboardEntryRow };
import SeqRow from "./seq_table";
export { SeqRow };
import SessionRow from "./session_table";
export { SessionRow };
import StepsSinceLastAuthFrameRow from "./steps_since_last_auth_frame_table";
export { StepsSinceLastAuthFrameRow };
import StepsSinceLastBatchRow from "./steps_since_last_batch_table";
export { StepsSinceLastBatchRow };
import ThroneRow from "./throne_table";
export { ThroneRow };
import ThroneTileDataRow from "./throne_tile_data_table";
export { ThroneTileDataRow };

// Import and reexport all types
import Account from "./account_type";
export { Account };
import AccountBid from "./account_bid_type";
export { AccountBid };
import AccountCustomization from "./account_customization_type";
export { AccountCustomization };
import AccountSeq from "./account_seq_type";
export { AccountSeq };
import Admin from "./admin_type";
export { Admin };
import AuthFrame from "./auth_frame_type";
export { AuthFrame };
import BaseCfg from "./base_cfg_type";
export { BaseCfg };
import BidConfigS from "./bid_config_s_type";
export { BidConfigS };
import BidTimeS from "./bid_time_s_type";
export { BidTimeS };
import BiddingStateS from "./bidding_state_s_type";
export { BiddingStateS };
import Clock from "./clock_type";
export { Clock };
import ClockSchedule from "./clock_schedule_type";
export { ClockSchedule };
import DeterminismCheck from "./determinism_check_type";
export { DeterminismCheck };
import GtScoreboardS from "./gt_scoreboard_s_type";
export { GtScoreboardS };
import GameCoreSnap from "./game_core_snap_type";
export { GameCoreSnap };
import GameTileData from "./game_tile_data_type";
export { GameTileData };
import InputCollector from "./input_collector_type";
export { InputCollector };
import InputFrame from "./input_frame_type";
export { InputFrame };
import LastAuthFrameTimestamp from "./last_auth_frame_timestamp_type";
export { LastAuthFrameTimestamp };
import MySessionKindContainer from "./my_session_kind_container_type";
export { MySessionKindContainer };
import ScoreboardEntry from "./scoreboard_entry_type";
export { ScoreboardEntry };
import Seq from "./seq_type";
export { Seq };
import Session from "./session_type";
export { Session };
import SessionKind from "./session_kind_type";
export { SessionKind };
import StepsSinceLastAuthFrame from "./steps_since_last_auth_frame_type";
export { StepsSinceLastAuthFrame };
import StepsSinceLastBatch from "./steps_since_last_batch_type";
export { StepsSinceLastBatch };
import Throne from "./throne_type";
export { Throne };
import ThroneTileData from "./throne_tile_data_type";
export { ThroneTileData };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'Account',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'Account_Id_key', constraint: 'unique', columns: ['id'] },
      { name: 'Account_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountRow),
  __table({
    name: 'AccountBid',
    indexes: [
      { name: 'AccountId', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'AccountBid_AccountId_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, AccountBidRow),
  __table({
    name: 'AccountCustomization',
    indexes: [
      { name: 'AccountId', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'AccountCustomization_AccountId_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, AccountCustomizationRow),
  __table({
    name: 'AccountSeq',
    indexes: [
      { name: 'IdS', algorithm: 'btree', columns: [
        'idS',
      ] },
    ],
    constraints: [
      { name: 'AccountSeq_IdS_key', constraint: 'unique', columns: ['idS'] },
    ],
  }, AccountSeqRow),
  __table({
    name: 'Admin',
    indexes: [
      { name: 'AdminIdentity', algorithm: 'btree', columns: [
        'adminIdentity',
      ] },
    ],
    constraints: [
      { name: 'Admin_AdminIdentity_key', constraint: 'unique', columns: ['adminIdentity'] },
    ],
  }, AdminRow),
  __table({
    name: 'AuthFrame',
    indexes: [
      { name: 'Seq', algorithm: 'btree', columns: [
        'seq',
      ] },
    ],
    constraints: [
      { name: 'AuthFrame_Seq_key', constraint: 'unique', columns: ['seq'] },
    ],
  }, AuthFrameRow),
  __table({
    name: 'BaseCfg',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'BaseCfg_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BaseCfgRow),
  __table({
    name: 'BidConfigS',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'BidConfigS_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BidConfigSRow),
  __table({
    name: 'BidTimeS',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'BidTimeS_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BidTimeSRow),
  __table({
    name: 'BiddingStateS',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'BiddingStateS_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BiddingStateSRow),
  __table({
    name: 'Clock',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'Clock_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClockRow),
  __table({
    name: 'ClockSchedule',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ClockSchedule_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClockScheduleRow),
  __table({
    name: 'DeterminismCheck',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'DeterminismCheck_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DeterminismCheckRow),
  __table({
    name: 'GTScoreboardS',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'GTScoreboardS_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GtScoreboardSRow),
  __table({
    name: 'GameCoreSnap',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'GameCoreSnap_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameCoreSnapRow),
  __table({
    name: 'GameTileData',
    indexes: [
      { name: 'UnityPrefabGUID', algorithm: 'btree', columns: [
        'unityPrefabGuid',
      ] },
    ],
    constraints: [
      { name: 'GameTileData_UnityPrefabGUID_key', constraint: 'unique', columns: ['unityPrefabGuid'] },
    ],
  }, GameTileDataRow),
  __table({
    name: 'InputCollector',
    indexes: [
    ],
    constraints: [
    ],
  }, InputCollectorRow),
  __table({
    name: 'InputFrame',
    indexes: [
      { name: 'Seq', algorithm: 'btree', columns: [
        'seq',
      ] },
    ],
    constraints: [
      { name: 'InputFrame_Seq_key', constraint: 'unique', columns: ['seq'] },
    ],
  }, InputFrameRow),
  __table({
    name: 'LastAuthFrameTimestamp',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'LastAuthFrameTimestamp_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LastAuthFrameTimestampRow),
  __table({
    name: 'ScoreboardEntry',
    indexes: [
      { name: 'AccountId', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'ScoreboardEntry_AccountId_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, ScoreboardEntryRow),
  __table({
    name: 'Seq',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'Seq_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SeqRow),
  __table({
    name: 'Session',
    indexes: [
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'Session_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SessionRow),
  __table({
    name: 'StepsSinceLastAuthFrame',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'StepsSinceLastAuthFrame_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StepsSinceLastAuthFrameRow),
  __table({
    name: 'StepsSinceLastBatch',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'StepsSinceLastBatch_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StepsSinceLastBatchRow),
  __table({
    name: 'Throne',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'Throne_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ThroneRow),
  __table({
    name: 'ThroneTileData',
    indexes: [
      { name: 'UnityPrefabGUID', algorithm: 'btree', columns: [
        'unityPrefabGuid',
      ] },
    ],
    constraints: [
      { name: 'ThroneTileData_UnityPrefabGUID_key', constraint: 'unique', columns: ['unityPrefabGuid'] },
    ],
  }, ThroneTileDataRow),
  __table({
    name: 'MyAccount',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  __table({
    name: 'MySessionKind',
    indexes: [
    ],
    constraints: [
    ],
  }, MySessionKindRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("A_GiveMarbles", AGiveMarbles),
  __reducerSchema("A_InsertBid", AInsertBid),
  __reducerSchema("A_SpinLoadGameplayTile", ASpinLoadGameplayTile),
  __reducerSchema("ClockUpdate", ClockUpdate),
  __reducerSchema("IncrementPfpVersion", IncrementPfpVersion),
  __reducerSchema("PlaceBid", PlaceBid),
  __reducerSchema("SetUsername", SetUsername),
  __reducerSchema("UpsertAccount", UpsertAccount),
  __reducerSchema("UpsertAccountSeq", UpsertAccountSeq),
  __reducerSchema("UpsertAuthFrame", UpsertAuthFrame),
  __reducerSchema("UpsertBaseCfg", UpsertBaseCfg),
  __reducerSchema("UpsertGameTile", UpsertGameTile),
  __reducerSchema("UpsertInputCollector", UpsertInputCollector),
  __reducerSchema("UpsertInputFrame", UpsertInputFrame),
  __reducerSchema("UpsertThroneTile", UpsertThroneTile),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

