// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AAttackThroneHandler(ReducerEventContext ctx, ulong accountId);
        public event AAttackThroneHandler? OnAAttackThrone;

        public void AAttackThrone(ulong accountId)
        {
            conn.InternalCallReducer(new Reducer.AAttackThrone(accountId), this.SetCallReducerFlags.AAttackThroneFlags);
        }

        public bool InvokeAAttackThrone(ReducerEventContext ctx, Reducer.AAttackThrone args)
        {
            if (OnAAttackThrone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAAttackThrone(
                ctx,
                args.AccountId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AAttackThrone : Reducer, IReducerArgs
        {
            [DataMember(Name = "accountId")]
            public ulong AccountId;

            public AAttackThrone(ulong AccountId)
            {
                this.AccountId = AccountId;
            }

            public AAttackThrone()
            {
            }

            string IReducerArgs.ReducerName => "A_AttackThrone";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AAttackThroneFlags;
        public void AAttackThrone(CallReducerFlags flags) => AAttackThroneFlags = flags;
    }
}
