// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AGiveMarblesHandler(ReducerEventContext ctx, ulong accountId, uint marbles);
        public event AGiveMarblesHandler? OnAGiveMarbles;

        public void AGiveMarbles(ulong accountId, uint marbles)
        {
            conn.InternalCallReducer(new Reducer.AGiveMarbles(accountId, marbles), this.SetCallReducerFlags.AGiveMarblesFlags);
        }

        public bool InvokeAGiveMarbles(ReducerEventContext ctx, Reducer.AGiveMarbles args)
        {
            if (OnAGiveMarbles == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAGiveMarbles(
                ctx,
                args.AccountId,
                args.Marbles
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AGiveMarbles : Reducer, IReducerArgs
        {
            [DataMember(Name = "accountId")]
            public ulong AccountId;
            [DataMember(Name = "marbles")]
            public uint Marbles;

            public AGiveMarbles(
                ulong AccountId,
                uint Marbles
            )
            {
                this.AccountId = AccountId;
                this.Marbles = Marbles;
            }

            public AGiveMarbles()
            {
            }

            string IReducerArgs.ReducerName => "A_GiveMarbles";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AGiveMarblesFlags;
        public void AGiveMarbles(CallReducerFlags flags) => AGiveMarblesFlags = flags;
    }
}
