// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AInsertBidHandler(ReducerEventContext ctx, ulong accountId, uint bid);
        public event AInsertBidHandler? OnAInsertBid;

        public void AInsertBid(ulong accountId, uint bid)
        {
            conn.InternalCallReducer(new Reducer.AInsertBid(accountId, bid), this.SetCallReducerFlags.AInsertBidFlags);
        }

        public bool InvokeAInsertBid(ReducerEventContext ctx, Reducer.AInsertBid args)
        {
            if (OnAInsertBid == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAInsertBid(
                ctx,
                args.AccountId,
                args.Bid
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AInsertBid : Reducer, IReducerArgs
        {
            [DataMember(Name = "accountId")]
            public ulong AccountId;
            [DataMember(Name = "bid")]
            public uint Bid;

            public AInsertBid(
                ulong AccountId,
                uint Bid
            )
            {
                this.AccountId = AccountId;
                this.Bid = Bid;
            }

            public AInsertBid()
            {
            }

            string IReducerArgs.ReducerName => "A_InsertBid";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AInsertBidFlags;
        public void AInsertBid(CallReducerFlags flags) => AInsertBidFlags = flags;
    }
}
