// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ASetAccountStreakHandler(ReducerEventContext ctx, ulong accountId, ushort streak, long lastClaimDay);
        public event ASetAccountStreakHandler? OnASetAccountStreak;

        public void ASetAccountStreak(ulong accountId, ushort streak, long lastClaimDay)
        {
            conn.InternalCallReducer(new Reducer.ASetAccountStreak(accountId, streak, lastClaimDay), this.SetCallReducerFlags.ASetAccountStreakFlags);
        }

        public bool InvokeASetAccountStreak(ReducerEventContext ctx, Reducer.ASetAccountStreak args)
        {
            if (OnASetAccountStreak == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnASetAccountStreak(
                ctx,
                args.AccountId,
                args.Streak,
                args.LastClaimDay
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ASetAccountStreak : Reducer, IReducerArgs
        {
            [DataMember(Name = "accountId")]
            public ulong AccountId;
            [DataMember(Name = "streak")]
            public ushort Streak;
            [DataMember(Name = "lastClaimDay")]
            public long LastClaimDay;

            public ASetAccountStreak(
                ulong AccountId,
                ushort Streak,
                long LastClaimDay
            )
            {
                this.AccountId = AccountId;
                this.Streak = Streak;
                this.LastClaimDay = LastClaimDay;
            }

            public ASetAccountStreak()
            {
            }

            string IReducerArgs.ReducerName => "A_SetAccountStreak";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ASetAccountStreakFlags;
        public void ASetAccountStreak(CallReducerFlags flags) => ASetAccountStreakFlags = flags;
    }
}
