// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ASetUsernameHandler(ReducerEventContext ctx, ulong accountId, string username);
        public event ASetUsernameHandler? OnASetUsername;

        public void ASetUsername(ulong accountId, string username)
        {
            conn.InternalCallReducer(new Reducer.ASetUsername(accountId, username), this.SetCallReducerFlags.ASetUsernameFlags);
        }

        public bool InvokeASetUsername(ReducerEventContext ctx, Reducer.ASetUsername args)
        {
            if (OnASetUsername == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnASetUsername(
                ctx,
                args.AccountId,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ASetUsername : Reducer, IReducerArgs
        {
            [DataMember(Name = "accountId")]
            public ulong AccountId;
            [DataMember(Name = "username")]
            public string Username;

            public ASetUsername(
                ulong AccountId,
                string Username
            )
            {
                this.AccountId = AccountId;
                this.Username = Username;
            }

            public ASetUsername()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "A_SetUsername";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ASetUsernameFlags;
        public void ASetUsername(CallReducerFlags flags) => ASetUsernameFlags = flags;
    }
}
