// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ASetGameplayFinishedHandler(ReducerEventContext ctx, bool isGameplayFinished);
        public event ASetGameplayFinishedHandler? OnASetGameplayFinished;

        public void ASetGameplayFinished(bool isGameplayFinished)
        {
            conn.InternalCallReducer(new Reducer.ASetGameplayFinished(isGameplayFinished), this.SetCallReducerFlags.ASetGameplayFinishedFlags);
        }

        public bool InvokeASetGameplayFinished(ReducerEventContext ctx, Reducer.ASetGameplayFinished args)
        {
            if (OnASetGameplayFinished == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnASetGameplayFinished(
                ctx,
                args.IsGameplayFinished
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ASetGameplayFinished : Reducer, IReducerArgs
        {
            [DataMember(Name = "isGameplayFinished")]
            public bool IsGameplayFinished;

            public ASetGameplayFinished(bool IsGameplayFinished)
            {
                this.IsGameplayFinished = IsGameplayFinished;
            }

            public ASetGameplayFinished()
            {
            }

            string IReducerArgs.ReducerName => "A_SetGameplayFinished";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ASetGameplayFinishedFlags;
        public void ASetGameplayFinished(CallReducerFlags flags) => ASetGameplayFinishedFlags = flags;
    }
}
