// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ASpinLoadGameplayTileHandler(ReducerEventContext ctx, byte worldId);
        public event ASpinLoadGameplayTileHandler? OnASpinLoadGameplayTile;

        public void ASpinLoadGameplayTile(byte worldId)
        {
            conn.InternalCallReducer(new Reducer.ASpinLoadGameplayTile(worldId), this.SetCallReducerFlags.ASpinLoadGameplayTileFlags);
        }

        public bool InvokeASpinLoadGameplayTile(ReducerEventContext ctx, Reducer.ASpinLoadGameplayTile args)
        {
            if (OnASpinLoadGameplayTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnASpinLoadGameplayTile(
                ctx,
                args.WorldId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ASpinLoadGameplayTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "worldId")]
            public byte WorldId;

            public ASpinLoadGameplayTile(byte WorldId)
            {
                this.WorldId = WorldId;
            }

            public ASpinLoadGameplayTile()
            {
            }

            string IReducerArgs.ReducerName => "A_SpinLoadGameplayTile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ASpinLoadGameplayTileFlags;
        public void ASpinLoadGameplayTile(CallReducerFlags flags) => ASpinLoadGameplayTileFlags = flags;
    }
}
