// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AttackThroneHandler(ReducerEventContext ctx);
        public event AttackThroneHandler? OnAttackThrone;

        public void AttackThrone()
        {
            conn.InternalCallReducer(new Reducer.AttackThrone(), this.SetCallReducerFlags.AttackThroneFlags);
        }

        public bool InvokeAttackThrone(ReducerEventContext ctx, Reducer.AttackThrone args)
        {
            if (OnAttackThrone == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAttackThrone(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AttackThrone : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "AttackThrone";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AttackThroneFlags;
        public void AttackThrone(CallReducerFlags flags) => AttackThroneFlags = flags;
    }
}
