// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClockUpdateHandler(ReducerEventContext ctx, ClockSchedule schedule);
        public event ClockUpdateHandler? OnClockUpdate;

        public void ClockUpdate(ClockSchedule schedule)
        {
            conn.InternalCallReducer(new Reducer.ClockUpdate(schedule), this.SetCallReducerFlags.ClockUpdateFlags);
        }

        public bool InvokeClockUpdate(ReducerEventContext ctx, Reducer.ClockUpdate args)
        {
            if (OnClockUpdate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnClockUpdate(
                ctx,
                args.Schedule
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClockUpdate : Reducer, IReducerArgs
        {
            [DataMember(Name = "schedule")]
            public ClockSchedule Schedule;

            public ClockUpdate(ClockSchedule Schedule)
            {
                this.Schedule = Schedule;
            }

            public ClockUpdate()
            {
                this.Schedule = new();
            }

            string IReducerArgs.ReducerName => "ClockUpdate";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClockUpdateFlags;
        public void ClockUpdate(CallReducerFlags flags) => ClockUpdateFlags = flags;
    }
}
