// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CloseAndCycleGameTileHandler(ReducerEventContext ctx, byte worldId);
        public event CloseAndCycleGameTileHandler? OnCloseAndCycleGameTile;

        public void CloseAndCycleGameTile(byte worldId)
        {
            conn.InternalCallReducer(new Reducer.CloseAndCycleGameTile(worldId), this.SetCallReducerFlags.CloseAndCycleGameTileFlags);
        }

        public bool InvokeCloseAndCycleGameTile(ReducerEventContext ctx, Reducer.CloseAndCycleGameTile args)
        {
            if (OnCloseAndCycleGameTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCloseAndCycleGameTile(
                ctx,
                args.WorldId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CloseAndCycleGameTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "worldId")]
            public byte WorldId;

            public CloseAndCycleGameTile(byte WorldId)
            {
                this.WorldId = WorldId;
            }

            public CloseAndCycleGameTile()
            {
            }

            string IReducerArgs.ReducerName => "CloseAndCycleGameTile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CloseAndCycleGameTileFlags;
        public void CloseAndCycleGameTile(CallReducerFlags flags) => CloseAndCycleGameTileFlags = flags;
    }
}
