// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void IncrementPfpVersionHandler(ReducerEventContext ctx);
        public event IncrementPfpVersionHandler? OnIncrementPfpVersion;

        public void IncrementPfpVersion()
        {
            conn.InternalCallReducer(new Reducer.IncrementPfpVersion(), this.SetCallReducerFlags.IncrementPfpVersionFlags);
        }

        public bool InvokeIncrementPfpVersion(ReducerEventContext ctx, Reducer.IncrementPfpVersion args)
        {
            if (OnIncrementPfpVersion == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnIncrementPfpVersion(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class IncrementPfpVersion : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "IncrementPfpVersion";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags IncrementPfpVersionFlags;
        public void IncrementPfpVersion(CallReducerFlags flags) => IncrementPfpVersionFlags = flags;
    }
}
