// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceBidHandler(ReducerEventContext ctx, uint bid);
        public event PlaceBidHandler? OnPlaceBid;

        public void PlaceBid(uint bid)
        {
            conn.InternalCallReducer(new Reducer.PlaceBid(bid), this.SetCallReducerFlags.PlaceBidFlags);
        }

        public bool InvokePlaceBid(ReducerEventContext ctx, Reducer.PlaceBid args)
        {
            if (OnPlaceBid == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceBid(
                ctx,
                args.Bid
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceBid : Reducer, IReducerArgs
        {
            [DataMember(Name = "bid")]
            public uint Bid;

            public PlaceBid(uint Bid)
            {
                this.Bid = Bid;
            }

            public PlaceBid()
            {
            }

            string IReducerArgs.ReducerName => "PlaceBid";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlaceBidFlags;
        public void PlaceBid(CallReducerFlags flags) => PlaceBidFlags = flags;
    }
}
