// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TakeDeterminismSnapHandler(ReducerEventContext ctx, SpacetimeDB.Types.DeterminismSnapSchedule schedule);
        public event TakeDeterminismSnapHandler? OnTakeDeterminismSnap;

        public void TakeDeterminismSnap(SpacetimeDB.Types.DeterminismSnapSchedule schedule)
        {
            conn.InternalCallReducer(new Reducer.TakeDeterminismSnap(schedule), this.SetCallReducerFlags.TakeDeterminismSnapFlags);
        }

        public bool InvokeTakeDeterminismSnap(ReducerEventContext ctx, Reducer.TakeDeterminismSnap args)
        {
            if (OnTakeDeterminismSnap == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTakeDeterminismSnap(
                ctx,
                args.Schedule
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TakeDeterminismSnap : Reducer, IReducerArgs
        {
            [DataMember(Name = "schedule")]
            public DeterminismSnapSchedule Schedule;

            public TakeDeterminismSnap(DeterminismSnapSchedule Schedule)
            {
                this.Schedule = Schedule;
            }

            public TakeDeterminismSnap()
            {
                this.Schedule = new();
            }

            string IReducerArgs.ReducerName => "TakeDeterminismSnap";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TakeDeterminismSnapFlags;
        public void TakeDeterminismSnap(CallReducerFlags flags) => TakeDeterminismSnapFlags = flags;
    }
}
