// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestSerializationHandler(ReducerEventContext ctx);
        public event TestSerializationHandler? OnTestSerialization;

        public void TestSerialization()
        {
            conn.InternalCallReducer(new Reducer.TestSerialization(), this.SetCallReducerFlags.TestSerializationFlags);
        }

        public bool InvokeTestSerialization(ReducerEventContext ctx, Reducer.TestSerialization args)
        {
            if (OnTestSerialization == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnTestSerialization(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TestSerialization : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "TestSerialization";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestSerializationFlags;
        public void TestSerialization(CallReducerFlags flags) => TestSerializationFlags = flags;
    }
}
