// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertAccountSeqHandler(ReducerEventContext ctx, SpacetimeDB.Types.AccountSeq row);
        public event UpsertAccountSeqHandler? OnUpsertAccountSeq;

        public void UpsertAccountSeq(SpacetimeDB.Types.AccountSeq row)
        {
            conn.InternalCallReducer(new Reducer.UpsertAccountSeq(row), this.SetCallReducerFlags.UpsertAccountSeqFlags);
        }

        public bool InvokeUpsertAccountSeq(ReducerEventContext ctx, Reducer.UpsertAccountSeq args)
        {
            if (OnUpsertAccountSeq == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertAccountSeq(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertAccountSeq : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public AccountSeq Row;

            public UpsertAccountSeq(AccountSeq Row)
            {
                this.Row = Row;
            }

            public UpsertAccountSeq()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertAccountSeq";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertAccountSeqFlags;
        public void UpsertAccountSeq(CallReducerFlags flags) => UpsertAccountSeqFlags = flags;
    }
}
