// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertLevelFileDataHandler(ReducerEventContext ctx, LevelFileData levelFileData);
        public event UpsertLevelFileDataHandler? OnUpsertLevelFileData;

        public void UpsertLevelFileData(LevelFileData levelFileData)
        {
            conn.InternalCallReducer(new Reducer.UpsertLevelFileData(levelFileData), this.SetCallReducerFlags.UpsertLevelFileDataFlags);
        }

        public bool InvokeUpsertLevelFileData(ReducerEventContext ctx, Reducer.UpsertLevelFileData args)
        {
            if (OnUpsertLevelFileData == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertLevelFileData(
                ctx,
                args.LevelFileData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertLevelFileData : Reducer, IReducerArgs
        {
            [DataMember(Name = "levelFileData")]
            public LevelFileData LevelFileData;

            public UpsertLevelFileData(LevelFileData LevelFileData)
            {
                this.LevelFileData = LevelFileData;
            }

            public UpsertLevelFileData()
            {
                this.LevelFileData = new();
            }

            string IReducerArgs.ReducerName => "UpsertLevelFileData";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertLevelFileDataFlags;
        public void UpsertLevelFileData(CallReducerFlags flags) => UpsertLevelFileDataFlags = flags;
    }
}
