// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertInputFrameHandler(ReducerEventContext ctx, InputFrame row);
        public event UpsertInputFrameHandler? OnUpsertInputFrame;

        public void UpsertInputFrame(InputFrame row)
        {
            conn.InternalCallReducer(new Reducer.UpsertInputFrame(row), this.SetCallReducerFlags.UpsertInputFrameFlags);
        }

        public bool InvokeUpsertInputFrame(ReducerEventContext ctx, Reducer.UpsertInputFrame args)
        {
            if (OnUpsertInputFrame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnUpsertInputFrame(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertInputFrame : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public InputFrame Row;

            public UpsertInputFrame(InputFrame Row)
            {
                this.Row = Row;
            }

            public UpsertInputFrame()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertInputFrame";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertInputFrameFlags;
        public void UpsertInputFrame(CallReducerFlags flags) => UpsertInputFrameFlags = flags;
    }
}
