// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertAuthFrameHandler(ReducerEventContext ctx, SpacetimeDB.Types.AuthFrame row);
        public event UpsertAuthFrameHandler? OnUpsertAuthFrame;

        public void UpsertAuthFrame(SpacetimeDB.Types.AuthFrame row)
        {
            conn.InternalCallReducer(new Reducer.UpsertAuthFrame(row), this.SetCallReducerFlags.UpsertAuthFrameFlags);
        }

        public bool InvokeUpsertAuthFrame(ReducerEventContext ctx, Reducer.UpsertAuthFrame args)
        {
            if (OnUpsertAuthFrame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertAuthFrame(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertAuthFrame : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public AuthFrame Row;

            public UpsertAuthFrame(AuthFrame Row)
            {
                this.Row = Row;
            }

            public UpsertAuthFrame()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertAuthFrame";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertAuthFrameFlags;
        public void UpsertAuthFrame(CallReducerFlags flags) => UpsertAuthFrameFlags = flags;
    }
}
