// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertGameTileHandler(ReducerEventContext ctx, SpacetimeDB.Types.GameTile gameTileData);
        public event UpsertGameTileHandler? OnUpsertGameTile;

        public void UpsertGameTile(SpacetimeDB.Types.GameTile gameTileData)
        {
            conn.InternalCallReducer(new Reducer.UpsertGameTile(gameTileData), this.SetCallReducerFlags.UpsertGameTileFlags);
        }

        public bool InvokeUpsertGameTile(ReducerEventContext ctx, Reducer.UpsertGameTile args)
        {
            if (OnUpsertGameTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertGameTile(
                ctx,
                args.GameTileData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertGameTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "gameTileData")]
            public GameTile GameTileData;

            public UpsertGameTile(GameTile GameTileData)
            {
                this.GameTileData = GameTileData;
            }

            public UpsertGameTile()
            {
                this.GameTileData = new();
            }

            string IReducerArgs.ReducerName => "UpsertGameTile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertGameTileFlags;
        public void UpsertGameTile(CallReducerFlags flags) => UpsertGameTileFlags = flags;
    }
}
