// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertBaseCfgHandler(ReducerEventContext ctx, SpacetimeDB.Types.BaseCfg row);
        public event UpsertBaseCfgHandler? OnUpsertBaseCfg;

        public void UpsertBaseCfg(SpacetimeDB.Types.BaseCfg row)
        {
            conn.InternalCallReducer(new Reducer.UpsertBaseCfg(row), this.SetCallReducerFlags.UpsertBaseCfgFlags);
        }

        public bool InvokeUpsertBaseCfg(ReducerEventContext ctx, Reducer.UpsertBaseCfg args)
        {
            if (OnUpsertBaseCfg == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertBaseCfg(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertBaseCfg : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public BaseCfg Row;

            public UpsertBaseCfg(BaseCfg Row)
            {
                this.Row = Row;
            }

            public UpsertBaseCfg()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertBaseCfg";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertBaseCfgFlags;
        public void UpsertBaseCfg(CallReducerFlags flags) => UpsertBaseCfgFlags = flags;
    }
}
