// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertInputCollectorHandler(ReducerEventContext ctx, InputCollector row);
        public event UpsertInputCollectorHandler? OnUpsertInputCollector;

        public void UpsertInputCollector(InputCollector row)
        {
            conn.InternalCallReducer(new Reducer.UpsertInputCollector(row), this.SetCallReducerFlags.UpsertInputCollectorFlags);
        }

        public bool InvokeUpsertInputCollector(ReducerEventContext ctx, Reducer.UpsertInputCollector args)
        {
            if (OnUpsertInputCollector == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnUpsertInputCollector(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertInputCollector : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public InputCollector Row;

            public UpsertInputCollector(InputCollector Row)
            {
                this.Row = Row;
            }

            public UpsertInputCollector()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertInputCollector";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertInputCollectorFlags;
        public void UpsertInputCollector(CallReducerFlags flags) => UpsertInputCollectorFlags = flags;
    }
}
