// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertAccountHandler(ReducerEventContext ctx, Account row);
        public event UpsertAccountHandler? OnUpsertAccount;

        public void UpsertAccount(Account row)
        {
            conn.InternalCallReducer(new Reducer.UpsertAccount(row), this.SetCallReducerFlags.UpsertAccountFlags);
        }

        public bool InvokeUpsertAccount(ReducerEventContext ctx, Reducer.UpsertAccount args)
        {
            if (OnUpsertAccount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnUpsertAccount(
                ctx,
                args.Row
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertAccount : Reducer, IReducerArgs
        {
            [DataMember(Name = "row")]
            public Account Row;

            public UpsertAccount(Account Row)
            {
                this.Row = Row;
            }

            public UpsertAccount()
            {
                this.Row = new();
            }

            string IReducerArgs.ReducerName => "UpsertAccount";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertAccountFlags;
        public void UpsertAccount(CallReducerFlags flags) => UpsertAccountFlags = flags;
    }
}
