// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertGameTileDataHandler(ReducerEventContext ctx, GameTileData gameTileData);
        public event UpsertGameTileDataHandler? OnUpsertGameTileData;

        public void UpsertGameTileData(GameTileData gameTileData)
        {
            conn.InternalCallReducer(new Reducer.UpsertGameTileData(gameTileData), this.SetCallReducerFlags.UpsertGameTileDataFlags);
        }

        public bool InvokeUpsertGameTileData(ReducerEventContext ctx, Reducer.UpsertGameTileData args)
        {
            if (OnUpsertGameTileData == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason):
                            InternalOnUnhandledReducerError(ctx, new Exception(reason));
                            break;
                        case Status.OutOfEnergy(var _):
                            InternalOnUnhandledReducerError(ctx, new Exception("out of energy"));
                            break;
                    }
                }
                return false;
            }
            OnUpsertGameTileData(
                ctx,
                args.GameTileData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertGameTileData : Reducer, IReducerArgs
        {
            [DataMember(Name = "gameTileData")]
            public GameTileData GameTileData;

            public UpsertGameTileData(GameTileData GameTileData)
            {
                this.GameTileData = GameTileData;
            }

            public UpsertGameTileData()
            {
                this.GameTileData = new();
            }

            string IReducerArgs.ReducerName => "UpsertGameTileData";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertGameTileDataFlags;
        public void UpsertGameTileData(CallReducerFlags flags) => UpsertGameTileDataFlags = flags;
    }
}
