// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertThroneTileHandler(ReducerEventContext ctx, SpacetimeDB.Types.ThroneTileData throneTileData);
        public event UpsertThroneTileHandler? OnUpsertThroneTile;

        public void UpsertThroneTile(SpacetimeDB.Types.ThroneTileData throneTileData)
        {
            conn.InternalCallReducer(new Reducer.UpsertThroneTile(throneTileData), this.SetCallReducerFlags.UpsertThroneTileFlags);
        }

        public bool InvokeUpsertThroneTile(ReducerEventContext ctx, Reducer.UpsertThroneTile args)
        {
            if (OnUpsertThroneTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertThroneTile(
                ctx,
                args.ThroneTileData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertThroneTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "throneTileData")]
            public ThroneTileData ThroneTileData;

            public UpsertThroneTile(ThroneTileData ThroneTileData)
            {
                this.ThroneTileData = ThroneTileData;
            }

            public UpsertThroneTile()
            {
                this.ThroneTileData = new();
            }

            string IReducerArgs.ReducerName => "UpsertThroneTile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpsertThroneTileFlags;
        public void UpsertThroneTile(CallReducerFlags flags) => UpsertThroneTileFlags = flags;
    }
}
