// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "IsConnected")]
        public bool IsConnected;
        [DataMember(Name = "Marbles")]
        public uint Marbles;
        [DataMember(Name = "Points")]
        public uint Points;
        [DataMember(Name = "Gold")]
        public uint Gold;
        [DataMember(Name = "FirstLoginBonusClaimed")]
        public bool FirstLoginBonusClaimed;
        [DataMember(Name = "IsMember")]
        public bool IsMember;
        [DataMember(Name = "DailyRewardClaimStreak")]
        public long DailyRewardClaimStreak;
        [DataMember(Name = "LastDailyRewardClaimDay")]
        public long LastDailyRewardClaimDay;

        public Account(
            SpacetimeDB.Identity Identity,
            ulong Id,
            bool IsConnected,
            uint Marbles,
            uint Points,
            uint Gold,
            bool FirstLoginBonusClaimed,
            bool IsMember,
            long DailyRewardClaimStreak,
            long LastDailyRewardClaimDay
        )
        {
            this.Identity = Identity;
            this.Id = Id;
            this.IsConnected = IsConnected;
            this.Marbles = Marbles;
            this.Points = Points;
            this.Gold = Gold;
            this.FirstLoginBonusClaimed = FirstLoginBonusClaimed;
            this.IsMember = IsMember;
            this.DailyRewardClaimStreak = DailyRewardClaimStreak;
            this.LastDailyRewardClaimDay = LastDailyRewardClaimDay;
        }

        public Account()
        {
        }
    }
}
