// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountBid
    {
        [DataMember(Name = "AccountId")]
        public ulong AccountId;
        [DataMember(Name = "TotalBid")]
        public uint TotalBid;

        public AccountBid(
            ulong AccountId,
            uint TotalBid
        )
        {
            this.AccountId = AccountId;
            this.TotalBid = TotalBid;
        }

        public AccountBid()
        {
        }
    }
}
