// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountCustomization
    {
        [DataMember(Name = "AccountId")]
        public ulong AccountId;
        [DataMember(Name = "Username")]
        public string Username;
        [DataMember(Name = "PfpVersion")]
        public byte PfpVersion;

        public AccountCustomization(
            ulong AccountId,
            string Username,
            byte PfpVersion
        )
        {
            this.AccountId = AccountId;
            this.Username = Username;
            this.PfpVersion = PfpVersion;
        }

        public AccountCustomization()
        {
            this.Username = "";
        }
    }
}
