// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountSeq
    {
        [DataMember(Name = "IdS")]
        public ulong IdS;
        [DataMember(Name = "Seq")]
        public ulong Seq;

        public AccountSeq(
            ulong IdS,
            ulong Seq
        )
        {
            this.IdS = IdS;
            this.Seq = Seq;
        }

        public AccountSeq()
        {
        }
    }
}
