// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuthFrame
    {
        [DataMember(Name = "Seq")]
        public ushort Seq;
        [DataMember(Name = "Frames")]
        public System.Collections.Generic.List<InputFrame> Frames;

        public AuthFrame(
            ushort Seq,
            System.Collections.Generic.List<InputFrame> Frames
        )
        {
            this.Seq = Seq;
            this.Frames = Frames;
        }

        public AuthFrame()
        {
            this.Frames = new();
        }
    }
}
