// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseCfg
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "ClockIntervalSec")]
        public double ClockIntervalSec;
        [DataMember(Name = "DeterminismSnapIntervalSec")]
        public double DeterminismSnapIntervalSec;
        [DataMember(Name = "targetStepsPerSecond")]
        public ushort TargetStepsPerSecond;
        [DataMember(Name = "physicsStepsPerBatch")]
        public ushort PhysicsStepsPerBatch;
        [DataMember(Name = "stepsPerAuthFrame")]
        public ushort StepsPerAuthFrame;
        [DataMember(Name = "authFrameTimeErrorThresholdSec")]
        public double AuthFrameTimeErrorThresholdSec;
        [DataMember(Name = "logInputFrameTimes")]
        public bool LogInputFrameTimes;
        [DataMember(Name = "logAuthFrameTimeDiffs")]
        public bool LogAuthFrameTimeDiffs;
        [DataMember(Name = "gcCacheAccountTimeoutMinutes")]
        public double GcCacheAccountTimeoutMinutes;

        public BaseCfg(
            byte Id,
            double ClockIntervalSec,
            double DeterminismSnapIntervalSec,
            ushort TargetStepsPerSecond,
            ushort PhysicsStepsPerBatch,
            ushort StepsPerAuthFrame,
            double AuthFrameTimeErrorThresholdSec,
            bool LogInputFrameTimes,
            bool LogAuthFrameTimeDiffs,
            double GcCacheAccountTimeoutMinutes
        )
        {
            this.Id = Id;
            this.ClockIntervalSec = ClockIntervalSec;
            this.DeterminismSnapIntervalSec = DeterminismSnapIntervalSec;
            this.TargetStepsPerSecond = TargetStepsPerSecond;
            this.PhysicsStepsPerBatch = PhysicsStepsPerBatch;
            this.StepsPerAuthFrame = StepsPerAuthFrame;
            this.AuthFrameTimeErrorThresholdSec = AuthFrameTimeErrorThresholdSec;
            this.LogInputFrameTimes = LogInputFrameTimes;
            this.LogAuthFrameTimeDiffs = LogAuthFrameTimeDiffs;
            this.GcCacheAccountTimeoutMinutes = GcCacheAccountTimeoutMinutes;
        }

        public BaseCfg()
        {
        }
    }
}
