// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseCfgS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "ClockIntervalSec")]
        public double ClockIntervalSec;
        [DataMember(Name = "DeterminismSnapIntervalSec")]
        public double DeterminismSnapIntervalSec;
        [DataMember(Name = "targetStepsPerSecond")]
        public ushort TargetStepsPerSecond;
        [DataMember(Name = "physicsStepsPerBatch")]
        public ushort PhysicsStepsPerBatch;
        [DataMember(Name = "stepsPerAuthFrame")]
        public ushort StepsPerAuthFrame;
        [DataMember(Name = "authFrameTimeErrorThresholdSec")]
        public double AuthFrameTimeErrorThresholdSec;
        [DataMember(Name = "logInputFrameTimes")]
        public bool LogInputFrameTimes;
        [DataMember(Name = "logAuthFrameTimeDiffs")]
        public bool LogAuthFrameTimeDiffs;
        [DataMember(Name = "gcCacheAccountTimeoutMinutes")]
        public double GcCacheAccountTimeoutMinutes;
        [DataMember(Name = "dayRewardStreak1Marbles")]
        public ushort DayRewardStreak1Marbles;
        [DataMember(Name = "dayRewardStreak2Marbles")]
        public ushort DayRewardStreak2Marbles;
        [DataMember(Name = "dayRewardStreak3Marbles")]
        public ushort DayRewardStreak3Marbles;
        [DataMember(Name = "dayRewardStreak4Marbles")]
        public ushort DayRewardStreak4Marbles;
        [DataMember(Name = "dayRewardStreak5Marbles")]
        public ushort DayRewardStreak5Marbles;
        [DataMember(Name = "dayRewardStreak6Marbles")]
        public ushort DayRewardStreak6Marbles;
        [DataMember(Name = "dayRewardStreak7Marbles")]
        public ushort DayRewardStreak7Marbles;

        public BaseCfgS(
            byte Id,
            double ClockIntervalSec,
            double DeterminismSnapIntervalSec,
            ushort TargetStepsPerSecond,
            ushort PhysicsStepsPerBatch,
            ushort StepsPerAuthFrame,
            double AuthFrameTimeErrorThresholdSec,
            bool LogInputFrameTimes,
            bool LogAuthFrameTimeDiffs,
            double GcCacheAccountTimeoutMinutes,
            ushort DayRewardStreak1Marbles,
            ushort DayRewardStreak2Marbles,
            ushort DayRewardStreak3Marbles,
            ushort DayRewardStreak4Marbles,
            ushort DayRewardStreak5Marbles,
            ushort DayRewardStreak6Marbles,
            ushort DayRewardStreak7Marbles
        )
        {
            this.Id = Id;
            this.ClockIntervalSec = ClockIntervalSec;
            this.DeterminismSnapIntervalSec = DeterminismSnapIntervalSec;
            this.TargetStepsPerSecond = TargetStepsPerSecond;
            this.PhysicsStepsPerBatch = PhysicsStepsPerBatch;
            this.StepsPerAuthFrame = StepsPerAuthFrame;
            this.AuthFrameTimeErrorThresholdSec = AuthFrameTimeErrorThresholdSec;
            this.LogInputFrameTimes = LogInputFrameTimes;
            this.LogAuthFrameTimeDiffs = LogAuthFrameTimeDiffs;
            this.GcCacheAccountTimeoutMinutes = GcCacheAccountTimeoutMinutes;
            this.DayRewardStreak1Marbles = DayRewardStreak1Marbles;
            this.DayRewardStreak2Marbles = DayRewardStreak2Marbles;
            this.DayRewardStreak3Marbles = DayRewardStreak3Marbles;
            this.DayRewardStreak4Marbles = DayRewardStreak4Marbles;
            this.DayRewardStreak5Marbles = DayRewardStreak5Marbles;
            this.DayRewardStreak6Marbles = DayRewardStreak6Marbles;
            this.DayRewardStreak7Marbles = DayRewardStreak7Marbles;
        }

        public BaseCfgS()
        {
        }
    }
}
