// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BidConfigS
    {
        [DataMember(Name = "MinAuctionSpots")]
        public int MinAuctionSpots;
        [DataMember(Name = "MaxAcutionSpots")]
        public int MaxAcutionSpots;
        [DataMember(Name = "MaxRaffleDraws")]
        public int MaxRaffleDraws;

        public BidConfigS(
            int MinAuctionSpots,
            int MaxAcutionSpots,
            int MaxRaffleDraws
        )
        {
            this.MinAuctionSpots = MinAuctionSpots;
            this.MaxAcutionSpots = MaxAcutionSpots;
            this.MaxRaffleDraws = MaxRaffleDraws;
        }

        public BidConfigS()
        {
        }
    }
}
