// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BiddingStateS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "OtherTileReadyForBidding")]
        public bool OtherTileReadyForBidding;
        [DataMember(Name = "CurrBidWorldId")]
        public byte CurrBidWorldId;

        public BiddingStateS(
            byte Id,
            bool OtherTileReadyForBidding,
            byte CurrBidWorldId
        )
        {
            this.Id = Id;
            this.OtherTileReadyForBidding = OtherTileReadyForBidding;
            this.CurrBidWorldId = CurrBidWorldId;
        }

        public BiddingStateS()
        {
        }
    }
}
