// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BidTimeS
    {
        [DataMember(Name = "MicrosecondsRemaining")]
        public ulong MicrosecondsRemaining;

        public BidTimeS(ulong MicrosecondsRemaining)
        {
            this.MicrosecondsRemaining = MicrosecondsRemaining;
        }

        public BidTimeS()
        {
        }
    }
}
