// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BidTimeS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "MicrosecondsRemaining")]
        public long MicrosecondsRemaining;

        public BidTimeS(
            byte Id,
            long MicrosecondsRemaining
        )
        {
            this.Id = Id;
            this.MicrosecondsRemaining = MicrosecondsRemaining;
        }

        public BidTimeS()
        {
        }
    }
}
