// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Clock
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "PrevClockUpdate")]
        public SpacetimeDB.Timestamp PrevClockUpdate;
        [DataMember(Name = "TickTimeAccumulatorSec")]
        public float TickTimeAccumulatorSec;

        public Clock(
            byte Id,
            SpacetimeDB.Timestamp PrevClockUpdate,
            float TickTimeAccumulatorSec
        )
        {
            this.Id = Id;
            this.PrevClockUpdate = PrevClockUpdate;
            this.TickTimeAccumulatorSec = TickTimeAccumulatorSec;
        }

        public Clock()
        {
        }
    }
}
