// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DeterminismSnapS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "Seq")]
        public ushort Seq;
        [DataMember(Name = "HashString")]
        public string HashString;

        public DeterminismSnapS(
            byte Id,
            ushort Seq,
            string HashString
        )
        {
            this.Id = Id;
            this.Seq = Seq;
            this.HashString = HashString;
        }

        public DeterminismSnapS()
        {
            this.HashString = "";
        }
    }
}
