// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DynamicSps
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "LastBatchStartTime")]
        public SpacetimeDB.Timestamp LastBatchStartTime;
        [DataMember(Name = "ActualTPS")]
        public float ActualTps;

        public DynamicSps(
            byte Id,
            SpacetimeDB.Timestamp LastBatchStartTime,
            float ActualTps
        )
        {
            this.Id = Id;
            this.LastBatchStartTime = LastBatchStartTime;
            this.ActualTps = ActualTps;
        }

        public DynamicSps()
        {
        }
    }
}
