// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameTile
    {
        [DataMember(Name = "UnityPrefabGUID")]
        public string UnityPrefabGuid;
        [DataMember(Name = "TileName")]
        public string TileName;
        [DataMember(Name = "Rarity")]
        public int Rarity;
        [DataMember(Name = "MinAuctionSpots")]
        public int MinAuctionSpots;
        [DataMember(Name = "MaxAuctionSpots")]
        public int MaxAuctionSpots;
        [DataMember(Name = "MaxRaffleDraws")]
        public int MaxRaffleDraws;
        [DataMember(Name = "GameTileBinary")]
        public System.Collections.Generic.List<byte> GameTileBinary;

        public GameTile(
            string UnityPrefabGuid,
            string TileName,
            int Rarity,
            int MinAuctionSpots,
            int MaxAuctionSpots,
            int MaxRaffleDraws,
            System.Collections.Generic.List<byte> GameTileBinary
        )
        {
            this.UnityPrefabGuid = UnityPrefabGuid;
            this.TileName = TileName;
            this.Rarity = Rarity;
            this.MinAuctionSpots = MinAuctionSpots;
            this.MaxAuctionSpots = MaxAuctionSpots;
            this.MaxRaffleDraws = MaxRaffleDraws;
            this.GameTileBinary = GameTileBinary;
        }

        public GameTile()
        {
            this.UnityPrefabGuid = "";
            this.TileName = "";
            this.GameTileBinary = new();
        }
    }
}
