// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameCoreSnap
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "Seq")]
        public ushort Seq;
        [DataMember(Name = "BinaryData")]
        public System.Collections.Generic.List<byte> BinaryData;

        public GameCoreSnap(
            byte Id,
            ushort Seq,
            System.Collections.Generic.List<byte> BinaryData
        )
        {
            this.Id = Id;
            this.Seq = Seq;
            this.BinaryData = BinaryData;
        }

        public GameCoreSnap()
        {
            this.BinaryData = new();
        }
    }
}
