// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameBidCfg
    {
        [DataMember(Name = "MinAuctionSpots")]
        public ushort MinAuctionSpots;
        [DataMember(Name = "MaxAcutionSpots")]
        public ushort MaxAcutionSpots;
        [DataMember(Name = "MaxRaffleDraws")]
        public ushort MaxRaffleDraws;

        public GameBidCfg(
            ushort MinAuctionSpots,
            ushort MaxAcutionSpots,
            ushort MaxRaffleDraws
        )
        {
            this.MinAuctionSpots = MinAuctionSpots;
            this.MaxAcutionSpots = MaxAcutionSpots;
            this.MaxRaffleDraws = MaxRaffleDraws;
        }

        public GameBidCfg()
        {
        }
    }
}
