// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameTileData
    {
        [DataMember(Name = "UnityPrefabGUID")]
        public string UnityPrefabGuid;
        [DataMember(Name = "TileName")]
        public string TileName;
        [DataMember(Name = "Rarity")]
        public int Rarity;
        [DataMember(Name = "GameTileBinary")]
        public System.Collections.Generic.List<byte> GameTileBinary;

        public GameTileData(
            string UnityPrefabGuid,
            string TileName,
            int Rarity,
            System.Collections.Generic.List<byte> GameTileBinary
        )
        {
            this.UnityPrefabGuid = UnityPrefabGuid;
            this.TileName = TileName;
            this.Rarity = Rarity;
            this.GameTileBinary = GameTileBinary;
        }

        public GameTileData()
        {
            this.UnityPrefabGuid = "";
            this.TileName = "";
            this.GameTileBinary = new();
        }
    }
}
