// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameplayFinishedFlagS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "IsGameplayFinished")]
        public bool IsGameplayFinished;

        public GameplayFinishedFlagS(
            byte Id,
            bool IsGameplayFinished
        )
        {
            this.Id = Id;
            this.IsGameplayFinished = IsGameplayFinished;
        }

        public GameplayFinishedFlagS()
        {
        }
    }
}
