// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GtScoreboardS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "GTUnityPrefabGUID")]
        public string GtUnityPrefabGuid;
        [DataMember(Name = "Entries")]
        public System.Collections.Generic.List<ScoreboardEntry> Entries;

        public GtScoreboardS(
            byte Id,
            string GtUnityPrefabGuid,
            System.Collections.Generic.List<ScoreboardEntry> Entries
        )
        {
            this.Id = Id;
            this.GtUnityPrefabGuid = GtUnityPrefabGuid;
            this.Entries = Entries;
        }

        public GtScoreboardS()
        {
            this.GtUnityPrefabGuid = "";
            this.Entries = new();
        }
    }
}
