// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InputCollector
    {
        [DataMember(Name = "delaySeqs")]
        public ushort DelaySeqs;
        [DataMember(Name = "inputEvent")]
        public System.Collections.Generic.List<byte> InputEvent;

        public InputCollector(
            ushort DelaySeqs,
            System.Collections.Generic.List<byte> InputEvent
        )
        {
            this.DelaySeqs = DelaySeqs;
            this.InputEvent = InputEvent;
        }

        public InputCollector()
        {
            this.InputEvent = new();
        }
    }
}
