// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InputFrame
    {
        [DataMember(Name = "Seq")]
        public ushort Seq;
        [DataMember(Name = "InputEventsList")]
        public System.Collections.Generic.List<byte> InputEventsList;

        public InputFrame(
            ushort Seq,
            System.Collections.Generic.List<byte> InputEventsList
        )
        {
            this.Seq = Seq;
            this.InputEventsList = InputEventsList;
        }

        public InputFrame()
        {
            this.InputEventsList = new();
        }
    }
}
