// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LastAuthFrameTimestamp
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "LastAuthFrameTime")]
        public SpacetimeDB.Timestamp LastAuthFrameTime;

        public LastAuthFrameTimestamp(
            byte Id,
            SpacetimeDB.Timestamp LastAuthFrameTime
        )
        {
            this.Id = Id;
            this.LastAuthFrameTime = LastAuthFrameTime;
        }

        public LastAuthFrameTimestamp()
        {
        }
    }
}
