// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LevelFileData
    {
        [DataMember(Name = "UnityPrefabGUID")]
        public string UnityPrefabGuid;
        [DataMember(Name = "Rarity")]
        public int Rarity;
        [DataMember(Name = "LevelFileBinary")]
        public System.Collections.Generic.List<byte> LevelFileBinary;

        public LevelFileData(
            string UnityPrefabGuid,
            int Rarity,
            System.Collections.Generic.List<byte> LevelFileBinary
        )
        {
            this.UnityPrefabGuid = UnityPrefabGuid;
            this.Rarity = Rarity;
            this.LevelFileBinary = LevelFileBinary;
        }

        public LevelFileData()
        {
            this.UnityPrefabGuid = "";
            this.LevelFileBinary = new();
        }
    }
}
