// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NextGameBidCfgS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "GameBidCfg")]
        public GameBidCfg GameBidCfg;

        public NextGameBidCfgS(
            byte Id,
            GameBidCfg GameBidCfg
        )
        {
            this.Id = Id;
            this.GameBidCfg = GameBidCfg;
        }

        public NextGameBidCfgS()
        {
            this.GameBidCfg = new();
        }
    }
}
