// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ScoreboardEntry
    {
        [DataMember(Name = "AccountId")]
        public ulong AccountId;
        [DataMember(Name = "PointsEarned")]
        public int PointsEarned;

        public ScoreboardEntry(
            ulong AccountId,
            int PointsEarned
        )
        {
            this.AccountId = AccountId;
            this.PointsEarned = PointsEarned;
        }

        public ScoreboardEntry()
        {
        }
    }
}
