// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Seq
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "Value")]
        public ushort Value;

        public Seq(
            byte Id,
            ushort Value
        )
        {
            this.Id = Id;
            this.Value = Value;
        }

        public Seq()
        {
        }
    }
}
