// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServerCfgS
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "activeAccountEvectionScanIntervalSec")]
        public ushort ActiveAccountEvectionScanIntervalSec;

        public ServerCfgS(
            byte Id,
            ushort ActiveAccountEvectionScanIntervalSec
        )
        {
            this.Id = Id;
            this.ActiveAccountEvectionScanIntervalSec = ActiveAccountEvectionScanIntervalSec;
        }

        public ServerCfgS()
        {
        }
    }
}
