// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Session
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Kind")]
        public SessionKind Kind;
        [DataMember(Name = "HasJwt")]
        public bool HasJwt;
        [DataMember(Name = "Issuer")]
        public string Issuer;
        [DataMember(Name = "Subject")]
        public string Subject;
        [DataMember(Name = "ConnectedAt")]
        public SpacetimeDB.Timestamp ConnectedAt;

        public Session(
            SpacetimeDB.Identity Identity,
            SessionKind Kind,
            bool HasJwt,
            string Issuer,
            string Subject,
            SpacetimeDB.Timestamp ConnectedAt
        )
        {
            this.Identity = Identity;
            this.Kind = Kind;
            this.HasJwt = HasJwt;
            this.Issuer = Issuer;
            this.Subject = Subject;
            this.ConnectedAt = ConnectedAt;
        }

        public Session()
        {
            this.Issuer = "";
            this.Subject = "";
        }
    }
}
