// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Throne
    {
        [DataMember(Name = "Id")]
        public byte Id;
        [DataMember(Name = "KingAccountId")]
        public ulong? KingAccountId;

        public Throne(
            byte Id,
            ulong? KingAccountId
        )
        {
            this.Id = Id;
            this.KingAccountId = KingAccountId;
        }

        public Throne()
        {
        }
    }
}
