// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ThroneTileData
    {
        [DataMember(Name = "UnityPrefabGUID")]
        public string UnityPrefabGuid;
        [DataMember(Name = "TileName")]
        public string TileName;
        [DataMember(Name = "ThroneTileBinary")]
        public System.Collections.Generic.List<byte> ThroneTileBinary;

        public ThroneTileData(
            string UnityPrefabGuid,
            string TileName,
            System.Collections.Generic.List<byte> ThroneTileBinary
        )
        {
            this.UnityPrefabGuid = UnityPrefabGuid;
            this.TileName = TileName;
            this.ThroneTileBinary = ThroneTileBinary;
        }

        public ThroneTileData()
        {
            this.UnityPrefabGuid = "";
            this.TileName = "";
            this.ThroneTileBinary = new();
        }
    }
}
